// This file is auto-generated by @hey-api/openapi-ts

export type MarkSearchCriteria = {
    subjectId?: string;
    professorId?: string;
    studentId?: string;
};

export type MarkResponse = {
    id?: string;
    subject?: SubjectResponse;
    professor?: ProfessorResponse;
    student?: StudentResponse;
    value?: number;
    localDateTime?: string;
};

export type ProfessorResponse = {
    id?: string;
    firstName?: string;
    lastName?: string;
};

export type StudentResponse = {
    id?: string;
    firstName?: string;
    lastName?: string;
};

export type SubjectResponse = {
    id?: string;
    subjectName?: string;
};

export type DiplomaResponse = {
    firstName?: string;
    lastName?: string;
    elementarySchoolYears?: Array<SchoolYearResponse>;
    highSchoolYears?: Array<SchoolYearResponse>;
    ucn?: string;
};

export type SchoolYearResponse = {
    date?: string;
    subjects?: Array<SubjectResponse>;
    averageMark?: number;
};

export type GetMarksData = {
    body?: never;
    path?: never;
    query: {
        criteria: MarkSearchCriteria;
    };
    url: '/marks';
};

export type GetMarksResponses = {
    /**
     * OK
     */
    200: Array<MarkResponse>;
};

export type GetMarksResponse = GetMarksResponses[keyof GetMarksResponses];

export type GetDiplomaData = {
    body?: never;
    path: {
        personUCN: string;
    };
    query?: never;
    url: '/diplomas/person/{personUCN}';
};

export type GetDiplomaResponses = {
    /**
     * OK
     */
    200: DiplomaResponse;
};

export type GetDiplomaResponse = GetDiplomaResponses[keyof GetDiplomaResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};