services:
  mysql:
    image: 'mysql:8.0'
    container_name: eschool_mysql
    environment:
      - 'MYSQL_DATABASE=eschooldb'
      - 'MYSQL_PASSWORD=eschoolpw'
      - 'MYSQL_ROOT_PASSWORD=eschoolrootpw'
      - 'MYSQL_USER=eschooluser'
    ports:
      - '3306:3306'