services:
  mysqldb:
    container_name: eschool_mysqldb
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=eschooldb'
      - 'MYSQL_PASSWORD=eschoolpw'
      - 'MYSQL_ROOT_PASSWORD=eschoolrootpw'
      - 'MYSQL_USER=eschooluser'
    ports:
      - '3306:3306'
    networks:
      - eschool
    restart: unless-stopped

networks:
  eschool:
    driver: bridge